name: VoiceInk
options:
  bundleIdPrefix: com.voiceink
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    PRODUCT_NAME: VoiceInk
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

packages:
  HotKey:
    url: https://github.com/soffes/HotKey
    from: "0.2.1"
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: "4.2.2"
  LaunchAtLogin:
    url: https://github.com/sindresorhus/LaunchAtLogin-Modern
    from: "1.1.0"

targets:
  VoiceInk:
    type: application
    platform: macOS
    sources:
      - path: VoiceInk
        excludes:
          - "**/.DS_Store"
    info:
      path: VoiceInk/Info.plist
      properties:
        NSMicrophoneUsageDescription: "VoiceInk 需要使用麥克風來錄製語音並轉換為文字。"
        NSAppleEventsUsageDescription: "VoiceInk 需要輔助使用權限來偵測全域快捷鍵並自動貼上轉錄文字。"
    entitlements:
      path: VoiceInk/VoiceInk.entitlements
      properties:
        com.apple.security.device.audio-input: true
        com.apple.security.network.client: true
    settings:
      base:
        INFOPLIST_FILE: VoiceInk/Info.plist
        CODE_SIGN_ENTITLEMENTS: VoiceInk/VoiceInk.entitlements
        ENABLE_HARDENED_RUNTIME: YES
    dependencies:
      - package: HotKey
      - package: KeychainAccess
      - package: LaunchAtLogin
